# Workflow that runs unit test
name: CDK Nag Test

on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  cdk-nag:
    name: CDK Nag Check
    if: ${{ (github.repository_owner != 'lindar-joy' && github.event_name == 'push') || (github.repository_owner == 'lindar-joy' && github.event_name == 'pull_request') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd source/constructs && npm i --only=dev
          npm run cdk synth
